# Generated by Django 5.1.6 on 2025-03-07 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emial',
            new_name='email',
        ),
    ]
